/// <reference path="./pi-coding-agent.d.ts" />
import { defineTool, type ExtensionAPI, type ExtensionCommandContext } from "@mariozechner/pi-coding-agent";
import { Type } from "@sinclair/typebox";
import { readFileSync } from "node:fs";
import path from "node:path";

/**
 * pi-kuri — Kuri browser automation extension for Pi.
 *
 * Provides tools and commands for driving Kuri's HTTP API:
 *   - Browser navigation, snapshots, click, type, fill, select, scroll
 *   - Screenshots, page text, markdown, links extraction
 *   - Cookie/security audits
 *   - Session-based agent loops via X-Kuri-Session
 *
 * Configuration (set via env or pi config):
 *   KURI_BASE_URL   default: http://127.0.0.1:8080
 *   KURI_SESSION    default: pi-kuri-session
 */

const PI_KURI_EXTENSION_VERSION = "2026-05-20";

// ── Help text ─────────────────────────────────────────────────────────────

const COMMAND_HELP = [
  "/kuri - open the Kuri command picker (start, navigate, snap, click, audit)",
  "/kuri-help - show registered Kuri commands",
  `/extension version: ${PI_KURI_EXTENSION_VERSION}`,
];

const MENU_CHOICES = [
  "kuri-start - start the Kuri server (if not already running)",
  "kuri-health - check if Kuri server is running",
  "kuri-tab-new <url> - open a new tab and navigate to a URL",
  "kuri-navigate <url> - navigate current tab to a URL",
  "kuri-snap - get accessibility snapshot (interactive refs)",
  "kuri-page-info - get current page URL, title, ready state",
  "kuri-click <ref> - click an element by its eN ref",
  "kuri-type <ref> <text> - type text into an element",
  "kuri-fill <ref> <text> - fill an input value",
  "kuri-select <ref> <value> - select a dropdown option",
  "kuri-screenshot - capture a screenshot",
  "kuri-markdown - get page as markdown",
  "kuri-links - extract all links from the current page",
  "kuri-text - extract page text",
  "kuri-evaluate <js> - execute JavaScript in the page",
  "kuri-cookies - list cookies with security flags",
  "kuri-headers - check security response headers",
  "kuri-audit - run full security audit",
  "kuri-back - browser back",
  "kuri-forward - browser forward",
  "kuri-reload - reload the page",
  "kuri-session <id> - set the active Kuri session",
  "kuri-base <url> - set the Kuri server base URL",
  "kuri-token [token] - show or set the Kuri API auth token",
];

// ── Configuration helpers ─────────────────────────────────────────────────

function kuriBaseUrl(): string {
  return process.env.KURI_BASE_URL || "http://127.0.0.1:8080";
}

function kuriSession(): string {
  return process.env.KURI_SESSION || "pi-kuri-session";
}

function kuriAuthToken(): string | undefined {
  // 1. Try explicit env vars
  if (process.env.KURI_SECRET) return process.env.KURI_SECRET;
  if (process.env.KURI_API_TOKEN) return process.env.KURI_API_TOKEN;
  // 2. Read from api.token file (auto-generated by new Kuri builds)
  try {
    const homedir = process.env.HOME || process.env.HOMEPATH || "";
    return readFileSync(`${homedir}/.kuri/api.token`, "utf-8").trim();
  } catch {
    return undefined;
  }
}

function kuriHeaders(): Record<string, string> {
  const headers: Record<string, string> = {
    "X-Kuri-Session": kuriSession(),
    "Accept": "application/json",
  };
  const token = kuriAuthToken();
  if (token) {
    headers["Authorization"] = `Bearer ${token}`;
  }
  return headers;
}

function parseSiteScalar(value: string): string {
  const clean = value.trim().replace(/\s+#.*$/, "").trim();
  if ((clean.startsWith('"') && clean.endsWith('"')) || (clean.startsWith("'") && clean.endsWith("'"))) {
    return clean.slice(1, -1);
  }
  return clean;
}

function readSiteManifest(projectRoot: string): any {
  const manifestPath = path.join(projectRoot, ".sandcastle", "site-manifest.yaml");
  const raw = readFileSync(manifestPath, "utf-8");
  const manifest: any = { pages: {}, auth: {}, kuri: {} };
  let section = "";
  let pageName = "";
  for (const line of raw.split(/\r?\n/)) {
    if (!line.trim() || line.trim().startsWith("#")) continue;
    const top = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (top) {
      section = top[1];
      pageName = "";
      if (top[2]) manifest[section] = parseSiteScalar(top[2]);
      else if (section === "pages") manifest.pages = manifest.pages || {};
      else if (section === "auth") manifest.auth = manifest.auth || {};
      else if (section === "kuri") manifest.kuri = manifest.kuri || {};
      continue;
    }
    const nested = line.match(/^\s{2}([A-Za-z0-9_-]+):\s*(.*)$/);
    if (nested && section === "pages") {
      pageName = nested[1];
      manifest.pages[pageName] = nested[2] ? { url: parseSiteScalar(nested[2]) } : {};
      continue;
    }
    if (nested && (section === "auth" || section === "kuri")) {
      manifest[section][nested[1]] = parseSiteScalar(nested[2]);
      continue;
    }
    const pageField = line.match(/^\s{4}([A-Za-z0-9_-]+):\s*(.*)$/);
    if (pageField && section === "pages" && pageName) {
      manifest.pages[pageName][pageField[1]] = parseSiteScalar(pageField[2]);
    }
  }
  return manifest;
}

async function kuriFetch(path: string, query: Record<string, string> = {}): Promise<Response> {
  const base = kuriBaseUrl().replace(/\/+$/, "");
  const params = new URLSearchParams(query).toString();
  const url = `${base}${path}${params ? `?${params}` : ""}`;
  return fetch(url, { headers: kuriHeaders(), signal: AbortSignal.timeout(30_000) });
}

async function kuriFetchText(path: string, query: Record<string, string> = {}): Promise<string> {
  const resp = await kuriFetch(path, query);
  if (!resp.ok) {
    const body = await resp.text().catch(() => "");
    throw new Error(`Kuri ${path}: ${resp.status} ${resp.statusText} — ${body.slice(0, 200)}`);
  }
  return resp.text();
}

/**
 * Retry wrapper for CDP-fragile endpoints (page/info, screenshot, evaluate, markdown, etc.).
 * Retries up to maxRetries times with 1s exponential backoff on 502 (CDP failure).
 */
async function kuriFetchTextWithRetry(path: string, query: Record<string, string> = {}, maxRetries = 2): Promise<string> {
  let lastError: Error | null = null;
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      return await kuriFetchText(path, query);
    } catch (err: any) {
      const isCdpFailure = err.message?.includes("502") || err.message?.includes("CDP");
      if (isCdpFailure && attempt < maxRetries) {
        lastError = err;
        const delay = (attempt + 1) * 1000;
        await new Promise(r => setTimeout(r, delay));
        continue;
      }
      throw err;
    }
  }
  throw lastError || new Error(`Kuri ${path}: max retries exceeded`);
}

/**
 * Resolve the current session tab ID by calling /page/info.
 * Returns the tab_id string or throws if unavailable.
 */
async function resolveSessionTabId(): Promise<string> {
  const infoText = await kuriFetchTextWithRetry("/page/info", {});
  const info = JSON.parse(infoText);
  if (info.tab_id) return String(info.tab_id);
  throw new Error("Could not resolve current session tab ID");
}

function singleQuotedJsString(value: string): string {
  return `'${String(value).replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\r/g, "\\r").replace(/\n/g, "\\n")}'`;
}

function loginPageWarning(pageInfo: any, text: string, expectedUrl: string): string {
  const finalUrl = String(pageInfo?.url || "");
  const title = String(pageInfo?.title || "");
  const lowerText = String(text || "").toLowerCase();
  const compactText = lowerText.replace(/\s+/g, " ").trim();
  const hasLoginAction = /\b(log\s*in|login|sign\s*in|authenticate)\b/.test(`${title} ${compactText}`);
  const urlLooksLogin = /\/login\b|login\.php|auth|authenticate/i.test(finalUrl);
  const titleLooksLogin = /\b(authenticate|login|sign in)\b/i.test(title);
  let expectedHash = "";
  let finalHash = "";
  try { expectedHash = new URL(expectedUrl).hash || ""; } catch { /* ignore */ }
  try { finalHash = new URL(finalUrl).hash || ""; } catch { /* ignore */ }
  const hashMismatch = Boolean(expectedHash && finalHash && expectedHash !== finalHash);
  const littleContent = compactText.length > 0 && compactText.length < 500;
  if ((urlLooksLogin || titleLooksLogin || hasLoginAction) && (littleContent || hashMismatch || urlLooksLogin || titleLooksLogin)) {
    return "There is strong evidence this capture may be an unauthenticated login page: little page content and login/authentication signals were detected. The reviewer should verify the provided screenshot is for the correct page.";
  }
  return "";
}

async function checkKuriHealth(): Promise<boolean> {
  try {
    const resp = await kuriFetch("/health");
    return resp.ok;
  } catch {
    return false;
  }
}

// ── Tool definition helper ────────────────────────────────────────────────

/**
 * Wraps defineTool to give `execute` a typed `params` argument.
 * The type is inferred from the TypeBox schema via the `S` generic.
 */
function kuriTool<S extends ReturnType<typeof Type.Object>>(
  def: Omit<Parameters<typeof defineTool>[0], "parameters" | "execute"> & {
    parameters: S;
    execute: (
      toolCallId: string,
      params: Record<string, unknown>,
      signal: AbortSignal,
      onUpdate: (update: unknown) => void,
    ) => Promise<unknown> | unknown;
  },
) {
  return defineTool(def);
}

// ── Tool definitions ──────────────────────────────────────────────────────

const kuriNavigateTool = kuriTool({
  name: "kuri_navigate",
  label: "Navigate Browser",
  description: "Navigate a Kuri browser tab to a URL and return the page info.",
  promptSnippet: "Navigate browser to a URL",
  promptGuidelines: [
    "Use kuri_navigate to open a web page in the Kuri-controlled browser.",
    "After navigation, take a snapshot to get interactive element refs.",
  ],
  parameters: Type.Object({
    url: Type.String({ description: "The URL to navigate to" }),
    tab_id: Type.Optional(Type.String({ description: "Optional explicit tab ID. Defaults to session tab." })),
  }),
  execute: async (_toolCallId, params, _signal, _onUpdate) => {
    const query: Record<string, string> = { url: String(params.url) };
    if (params.tab_id) query.tab_id = String(params.tab_id);
    const text = await kuriFetchText("/navigate", query);
    return { content: [{ type: "text" as const, text }] };
  },
});

const kuriSnapTool = kuriTool({
  name: "kuri_snap",
  label: "Browser Snapshot",
  description: "Get an accessibility snapshot of the current page with interactive element refs (eN). Use filter=interactive&format=compact for low-token agent loops.",
  promptSnippet: "Get browser accessibility snapshot",
  promptGuidelines: [
    "Use kuri_snap after navigation to get clickable/typeable element references.",
    "Each element has a ref like e0, e1, e2 that can be used with kuri_click, kuri_type, etc.",
    "Filter to 'interactive' to get only clickable/typeable elements.",
    "Use format 'compact' for minimal token usage.",
    "Re-snap after any significant interaction — refs are snapshot-local.",
  ],
  parameters: Type.Object({
    filter: Type.Optional(Type.String({ description: "Filter: 'interactive' (default) or 'all'" })),
    format: Type.Optional(Type.String({ description: "Format: 'compact' (default) or 'json'" })),
    tab_id: Type.Optional(Type.String({ description: "Optional explicit tab ID." })),
  }),
  execute: async (_toolCallId, params, _signal, _onUpdate) => {
    const query: Record<string, string> = {
      filter: String(params.filter || "interactive"),
      format: String(params.format || "compact"),
    };
    if (params.tab_id) query.tab_id = String(params.tab_id);
    const text = await kuriFetchText("/snapshot", query);
    return { content: [{ type: "text" as const, text }] };
  },
});

const kuriClickTool = kuriTool({
  name: "kuri_click",
  label: "Click Browser Element",
  description: "Click an element in the browser by its accessibility snapshot ref (e.g. e0, e1).",
  promptSnippet: "Click browser element by ref",
  promptGuidelines: [
    "Use the ref from a kuri_snap snapshot (e.g. e0, e1, e2).",
    "Re-snap after clicking to get updated state.",
  ],
  parameters: Type.Object({
    ref: Type.String({ description: "Element ref from snapshot (e.g. 'e0', 'e1')" }),
    tab_id: Type.Optional(Type.String({ description: "Optional explicit tab ID." })),
  }),
  execute: async (_toolCallId, params, _signal, _onUpdate) => {
    const query: Record<string, string> = { action: "click", ref: String(params.ref) };
    if (params.tab_id) query.tab_id = String(params.tab_id);
    const text = await kuriFetchText("/action", query);
    return { content: [{ type: "text" as const, text }] };
  },
});

const kuriTypeTool = kuriTool({
  name: "kuri_type",
  label: "Type in Browser",
  description: "Type text into an element by its accessibility snapshot ref.",
  promptSnippet: "Type text into browser element",
  promptGuidelines: [
    "Use the ref from a kuri_snap snapshot.",
    "Clears existing text before typing by default.",
  ],
  parameters: Type.Object({
    ref: Type.String({ description: "Element ref from snapshot (e.g. 'e0')" }),
    value: Type.String({ description: "Text to type into the element" }),
    tab_id: Type.Optional(Type.String({ description: "Optional explicit tab ID." })),
  }),
  execute: async (_toolCallId, params, _signal, _onUpdate) => {
    const query: Record<string, string> = {
      action: "type",
      ref: String(params.ref),
      value: String(params.value),
    };
    if (params.tab_id) query.tab_id = String(params.tab_id);
    const text = await kuriFetchText("/action", query);
    return { content: [{ type: "text" as const, text }] };
  },
});

const kuriFillTool = kuriTool({
  name: "kuri_fill",
  label: "Fill Input in Browser",
  description: "Fill an input element's value (sets value directly, no key events).",
  promptSnippet: "Fill browser input element",
  parameters: Type.Object({
    ref: Type.String({ description: "Element ref from snapshot (e.g. 'e0')" }),
    value: Type.String({ description: "Value to set" }),
    tab_id: Type.Optional(Type.String({ description: "Optional explicit tab ID." })),
  }),
  execute: async (_toolCallId, params, _signal, _onUpdate) => {
    const query: Record<string, string> = {
      action: "fill",
      ref: String(params.ref),
      value: String(params.value),
    };
    if (params.tab_id) query.tab_id = String(params.tab_id);
    const text = await kuriFetchText("/action", query);
    return { content: [{ type: "text" as const, text }] };
  },
});

const kuriSelectTool = kuriTool({
  name: "kuri_select",
  label: "Select Dropdown Option",
  description: "Select an option from a dropdown/select element by ref.",
  promptSnippet: "Select dropdown option",
  parameters: Type.Object({
    ref: Type.String({ description: "Element ref from snapshot (e.g. 'e0')" }),
    value: Type.String({ description: "Option value to select" }),
    tab_id: Type.Optional(Type.String({ description: "Optional explicit tab ID." })),
  }),
  execute: async (_toolCallId, params, _signal, _onUpdate) => {
    const query: Record<string, string> = {
      action: "select",
      ref: String(params.ref),
      value: String(params.value),
    };
    if (params.tab_id) query.tab_id = String(params.tab_id);
    const text = await kuriFetchText("/action", query);
    return { content: [{ type: "text" as const, text }] };
  },
});

const kuriPageInfoTool = kuriTool({
  name: "kuri_page_info",
  label: "Page Info",
  description: "Get current page URL, title, ready state, viewport, and scroll position.",
  promptSnippet: "Get current browser page info",
  parameters: Type.Object({
    tab_id: Type.Optional(Type.String({ description: "Optional explicit tab ID." })),
  }),
  execute: async (_toolCallId, params, _signal, _onUpdate) => {
    const query: Record<string, string> = {};
    if (params.tab_id) query.tab_id = String(params.tab_id);
    const text = await kuriFetchTextWithRetry("/page/info", query);
    return { content: [{ type: "text" as const, text }] };
  },
});

const kuriScreenshotTool = kuriTool({
  name: "kuri_screenshot",
  label: "Browser Screenshot",
  description: "Capture a browser screenshot (base64-encoded).",
  promptSnippet: "Capture browser screenshot",
  promptGuidelines: [
    "Use settle_ms when capturing heavy JS-rendered pages to allow content to finish loading.",
  ],
  parameters: Type.Object({
    format: Type.Optional(Type.String({ description: "Image format: 'png' (default) or 'jpeg'" })),
    quality: Type.Optional(Type.Integer({ description: "JPEG quality 1-100 (default: 80, only applies to jpeg)" })),
    tab_id: Type.Optional(Type.String({ description: "Optional explicit tab ID." })),
    settle_ms: Type.Optional(Type.Number({ description: "Milliseconds to wait after navigation before capture (default: 0). Use on heavy JS pages." })),
  }),
  execute: async (_toolCallId, params, _signal, _onUpdate) => {
    const query: Record<string, string> = {};
    if (params.format) query.format = String(params.format);
    if (params.quality !== undefined && params.quality !== null) query.quality = String(params.quality);
    if (params.tab_id) query.tab_id = String(params.tab_id);
    const settleMs = params.settle_ms ? Number(params.settle_ms) : 0;
    if (settleMs > 0) {
      await new Promise(r => setTimeout(r, settleMs));
    }
    const text = await kuriFetchTextWithRetry("/screenshot", query);
    return { content: [{ type: "text" as const, text }] };
  },
});

const kuriEvaluateTool = kuriTool({
  name: "kuri_evaluate",
  label: "Execute JavaScript",
  description: "Execute JavaScript in the browser page and get the result.",
  promptSnippet: "Execute JavaScript in browser",
  parameters: Type.Object({
    expression: Type.String({ description: "JavaScript expression to evaluate" }),
    tab_id: Type.Optional(Type.String({ description: "Optional explicit tab ID." })),
  }),
  execute: async (_toolCallId, params, _signal, _onUpdate) => {
    const query: Record<string, string> = { expression: String(params.expression) };
    if (params.tab_id) query.tab_id = String(params.tab_id);
    const text = await kuriFetchTextWithRetry("/evaluate", query);
    return { content: [{ type: "text" as const, text }] };
  },
});

const kuriMarkdownTool = kuriTool({
  name: "kuri_markdown",
  label: "Page as Markdown",
  description: "Convert the current page to Markdown.",
  promptSnippet: "Convert page to markdown",
  parameters: Type.Object({
    tab_id: Type.Optional(Type.String({ description: "Optional explicit tab ID. Auto-resolves if omitted." })),
  }),
  execute: async (_toolCallId, params, _signal, _onUpdate) => {
    const query: Record<string, string> = {};
    if (params.tab_id) {
      query.tab_id = String(params.tab_id);
    } else {
      // Auto-resolve current tab since Kuri backend requires tab_id for /markdown
      query.tab_id = await resolveSessionTabId();
    }
    const text = await kuriFetchTextWithRetry("/markdown", query);
    return { content: [{ type: "text" as const, text }] };
  },
});

const kuriLinksTool = kuriTool({
  name: "kuri_links",
  label: "Extract Page Links",
  description: "Extract all links from the current page.",
  promptSnippet: "Extract page links",
  parameters: Type.Object({
    tab_id: Type.Optional(Type.String({ description: "Optional explicit tab ID. Auto-resolves if omitted." })),
  }),
  execute: async (_toolCallId, params, _signal, _onUpdate) => {
    const query: Record<string, string> = {};
    if (params.tab_id) {
      query.tab_id = String(params.tab_id);
    } else {
      // Auto-resolve current tab since Kuri backend requires tab_id for /links
      query.tab_id = await resolveSessionTabId();
    }
    const text = await kuriFetchTextWithRetry("/links", query);
    return { content: [{ type: "text" as const, text }] };
  },
});

const kuriTextTool = kuriTool({
  name: "kuri_text",
  label: "Extract Page Text",
  description: "Extract plain text from the current page. Falls back to aria-labels and visible text if raw text is empty.",
  promptSnippet: "Extract page text",
  promptGuidelines: [
    "On JS-heavy SPAs, kuri_text may return empty string. The tool auto-falls back to aria-label extraction.",
    "If the result still seems sparse, try kuri_snap to see visible interactive elements.",
  ],
  parameters: Type.Object({
    tab_id: Type.Optional(Type.String({ description: "Optional explicit tab ID." })),
  }),
  execute: async (_toolCallId, params, _signal, _onUpdate) => {
    const query: Record<string, string> = {};
    if (params.tab_id) query.tab_id = String(params.tab_id);
    let rawText = await kuriFetchTextWithRetry("/text", query);
    let text = rawText;
    // Parse the JSON response to check if the extracted value is actually empty
    try {
      const parsed = JSON.parse(rawText);
      const extractedValue = parsed?.result?.result?.value || parsed?.result?.value || "";
      if (extractedValue && String(extractedValue).trim()) {
        text = String(extractedValue);
      } else {
        // Value is empty — trigger fallback
        text = "";
      }
    } catch {
      // Not JSON, use raw
    }
    // If extracted text is empty or whitespace-only, fall back to aria-labels
    // and visible leaf text via evaluate
    if (!text || !text.trim()) {
      try {
        const evalQuery: Record<string, string> = {
          expression: [
            "(function(){",
            "  var t=[];",
            "  var els=document.querySelectorAll('[aria-label],[role],a,button');",
            "  for(var i=0;i<els.length;i++){",
            "    var label=els[i].getAttribute('aria-label');",
            "    if(label&&label.trim()) t.push('['+els[i].tagName+'] '+label.trim().slice(0,120));",
            "  }",
            "  return t.length ? t.join('\\n') : document.title;",
            "  })()",
          ].join(""),
        };
        if (params.tab_id) evalQuery.tab_id = String(params.tab_id);
        const evalResult = await kuriFetchTextWithRetry("/evaluate", evalQuery);
        const parsed = JSON.parse(evalResult);
        const extracted = parsed?.result?.result?.value || parsed?.result?.value || "";
        if (extracted && String(extracted).trim()) {
          text = "[aria-label fallback]\n" + String(extracted);
        }
      } catch {
        // fallback failed — return original empty result
      }
    }
    return { content: [{ type: "text" as const, text }] };
  },
});

const kuriCookiesTool = kuriTool({
  name: "kuri_cookies",
  label: "Browser Cookies",
  description: "List browser cookies with security flags (Secure, HttpOnly, SameSite).",
  promptSnippet: "List browser cookies",
  parameters: Type.Object({
    tab_id: Type.Optional(Type.String({ description: "Optional explicit tab ID." })),
  }),
  execute: async (_toolCallId, params, _signal, _onUpdate) => {
    const query: Record<string, string> = {};
    if (params.tab_id) query.tab_id = String(params.tab_id);
    const text = await kuriFetchText("/cookies", query);
    return { content: [{ type: "text" as const, text }] };
  },
});

const kuriAuditTool = kuriTool({
  name: "kuri_audit",
  label: "Security Audit",
  description: "Run a full security audit on the current page: HTTPS, security headers, cookies exposed to JS.",
  promptSnippet: "Run browser security audit",
  parameters: Type.Object({
    tab_id: Type.Optional(Type.String({ description: "Optional explicit tab ID." })),
  }),
  execute: async (_toolCallId, params, _signal, _onUpdate) => {
    const query: Record<string, string> = {};
    if (params.tab_id) query.tab_id = String(params.tab_id);
    const text = await kuriFetchText("/audit", query);
    return { content: [{ type: "text" as const, text }] };
  },
});

const kuriNewTabTool = kuriTool({
  name: "kuri_new_tab",
  label: "New Browser Tab",
  description: "Create a new browser tab, optionally navigating to a URL.",
  promptSnippet: "Create new browser tab",
  parameters: Type.Object({
    url: Type.Optional(Type.String({ description: "URL to navigate to in the new tab" })),
    activate: Type.Optional(Type.String({ description: "Set as the active/session tab (default: true)" })),
  }),
  execute: async (_toolCallId, params, _signal, _onUpdate) => {
    const query: Record<string, string> = {};
    if (params.url) query.url = String(params.url);
    if (params.activate === "false") query.activate = "false";
    const text = await kuriFetchText("/tab/new", query);
    return { content: [{ type: "text" as const, text }] };
  },
});

const kuriScrollTool = kuriTool({
  name: "kuri_scroll",
  label: "Scroll Browser Page",
  description: "Scroll the page or a specific element. Direction: up, down, left, right.",
  promptSnippet: "Scroll browser page",
  parameters: Type.Object({
    ref: Type.Optional(Type.String({ description: "Element ref to scroll into view (optional). Scrolls page if omitted." })),
    direction: Type.Optional(Type.String({ description: "Scroll direction: 'up', 'down', 'left', 'right'" })),
    tab_id: Type.Optional(Type.String({ description: "Optional explicit tab ID." })),
  }),
  execute: async (_toolCallId, params, _signal, _onUpdate) => {
    const query: Record<string, string> = {};
    if (params.ref) { query.action = "scrollintoview"; query.ref = String(params.ref); }
    if (params.direction) query.direction = String(params.direction);
    if (params.tab_id) query.tab_id = String(params.tab_id);
    const text = await kuriFetchText(params.ref ? "/scrollintoview" : "/action", query);
    return { content: [{ type: "text" as const, text }] };
  },
});

const kuriScrollUpTool = kuriTool({
  name: "kuri_scroll_up",
  label: "Scroll Page Up",
  description: "Scroll the browser page up.",
  promptSnippet: "Scroll page up",
  parameters: Type.Object({
    tab_id: Type.Optional(Type.String({ description: "Optional explicit tab ID." })),
  }),
  execute: async (_toolCallId, params, _signal, _onUpdate) => {
    const query: Record<string, string> = { action: "scroll", direction: "up" };
    if (params.tab_id) query.tab_id = String(params.tab_id);
    const text = await kuriFetchText("/action", query);
    return { content: [{ type: "text" as const, text }] };
  },
});

const kuriScrollDownTool = kuriTool({
  name: "kuri_scroll_down",
  label: "Scroll Page Down",
  description: "Scroll the browser page down.",
  promptSnippet: "Scroll page down",
  parameters: Type.Object({
    tab_id: Type.Optional(Type.String({ description: "Optional explicit tab ID." })),
  }),
  execute: async (_toolCallId, params, _signal, _onUpdate) => {
    const query: Record<string, string> = { action: "scroll", direction: "down" };
    if (params.tab_id) query.tab_id = String(params.tab_id);
    const text = await kuriFetchText("/action", query);
    return { content: [{ type: "text" as const, text }] };
  },
});

const kuriScreenshotSiteTool = kuriTool({
  name: "kuri_screenshot_site",
  label: "Screenshot Authenticated Page (Site Manifest)",
  description: "One-shot full flow: use a page from .sandcastle/site-manifest.yaml or an explicit simulator URL, apply repository-defined auth, navigate, settle, and save a screenshot into Sandcastle evidence.",
  promptSnippet: "One-shot authenticated screenshot for verifier/reviewer evidence lanes. Prefer page=\"<name>\" or an explicit simulator URL before manual browser tools.",
  promptGuidelines: [
    "When your role is responsible for visual evidence and this tool is available, prefer kuri_screenshot_site before trying individual kuri_* tools or gui_* tools.",
    "This is the one-shot tool: it handles auth, navigation, settle timing, and PNG saving in a single call.",
    "",
    "Preferred: use a page name from .sandcastle/site-manifest.yaml:",
    '  kuri_screenshot_site page="alert-log"',
    '  kuri_screenshot_site page="dashboard"',
    "",
    "Also valid: use an explicit simulator URL when the ticket needs a per-worktree server:",
    '  kuri_screenshot_site url="$(sandstate sim-url KEY)/indexWEB-ODAS.php#alert-log"',
      "",
      "Avoid output/token unless the operator explicitly asks for an override. Never write evidence to Desktop.",
      "By default, the tool saves into .sandcastle/tickets/<task>/evidence/ when running inside a task worktree.",
      "The tool reports URL/title and warns when the capture looks like an unauthenticated login page; reviewers must inspect that warning before accepting evidence.",
      "",
      'Full-page capture: add full_page="true" to capture the entire scrollable document height.',
      '  kuri_screenshot_site page="dashboard" full_page="true"',
      '  kuri_screenshot_site url="http://..." full_page="true"',
      "",
      "Do NOT fall back to multi-step kuri_navigate + kuri_snap + kuri_screenshot unless",
    "kuri_screenshot_site fails with an error you cannot fix (e.g. auth failure, wrong page).",
    "Use gui_screenshot or gui_read only as a fallback when Kuri cannot reach the needed page or state.",
  ],
  parameters: Type.Object({
    page: Type.Optional(Type.String({ description: "Page name from site manifest (e.g. 'alert-log', 'dashboard', 'networking')" })),
    url: Type.Optional(Type.String({ description: "Explicit URL for simulator/per-worktree capture. Prefer page when .sandcastle/site-manifest.yaml has a matching page." })),
    project: Type.Optional(Type.String({ description: "Project root path (defaults to CWD). Used to find .sandcastle/site-manifest.yaml" })),
    output: Type.Optional(Type.String({ description: "Advanced override. Prefer the default ticket evidence path; never use Desktop." })),
    token: Type.Optional(Type.String({ description: "Advanced auth override. Prefer manifest auth and environment configuration." })),
    settle_ms: Type.Optional(Type.Number({ description: "Milliseconds to wait after navigation before screenshot (default: from manifest or 3000)" })),
    full_page: Type.Optional(Type.Boolean({
  description: "Capture the full scrollable page height (viewport resize + JPEG, default: true). Set to false to capture only the visible viewport.",
})),
    tab_id: Type.Optional(Type.String({ description: "Reuse an existing tab ID instead of creating a new one" })),
  }, { additionalProperties: false }),
  execute: async (_toolCallId, params, _signal, _onUpdate) => {
    const projectRoot = params.project ? String(params.project) : process.cwd();
    const outputPath = params.output ? String(params.output) : "";
    if (outputPath && /(^|\/)Desktop(\/|$)/i.test(outputPath.replace(/\\/g, "/"))) {
      return {
        content: [{
          type: "text" as const,
          text: "Refusing Desktop output path. Visual evidence must stay under the repository Sandcastle evidence area unless the operator explicitly asks for a different non-Desktop path.",
        }],
      };
    }
    const authToken = params.token ? String(params.token) : undefined;
    const settleMs = params.settle_ms ? Number(params.settle_ms) : undefined;
    const reuseTabId = params.tab_id ? String(params.tab_id) : undefined;
    const pageName = params.page ? String(params.page) : "";
    const explicitUrl = params.url ? String(params.url) : "";
    const fullPage = params.full_page !== false;

    // 1. Load site manifest or explicit URL target
    let manifest: any = null;
    let targetUrl = "";
    let manifestBaseUrl = "http://localhost:8082";
    let manifestSettleMs = 3000;
    if (explicitUrl) {
      targetUrl = explicitUrl;
      try {
        manifest = readSiteManifest(projectRoot);
      } catch { /* explicit URL can run without a site manifest */ }
      try {
        const u = new URL(explicitUrl);
        manifestBaseUrl = u.origin;
      } catch { /* keep default */ }
    } else if (pageName) {
      try {
        manifest = readSiteManifest(projectRoot);
        manifestBaseUrl = manifest.base_url || "http://localhost:8082";
        manifestSettleMs = settleMs ?? Number(manifest.kuri?.settle_ms || 3000);
        // Normalize: agent might pass underscores instead of hyphens
        const pageDef = manifest.pages?.[pageName] || manifest.pages?.[pageName.replace(/_/g, "-")];
        if (!pageDef) {
          const available = Object.keys(manifest.pages || {}).join(", ");
          return {
            content: [{ type: "text" as const, text: `Unknown page '${pageName}'. Available: ${available}` }],
          };
        }
        targetUrl = manifestBaseUrl.replace(/\/$/, "") + pageDef.url;
      } catch (err: any) {
        return {
          content: [{ type: "text" as const, text: `Failed to load site manifest: ${err.message}` }],
        };
      }
    } else {
      return {
        content: [{ type: "text" as const, text: 'Must provide page="<name>" from .sandcastle/site-manifest.yaml or url="<simulator-url>".' }],
      };
    }

    // 2. Read auth config
    const authMethod = manifest?.auth?.method || "none";
    const tokenEnv = manifest?.auth?.token_env || "DEV_SCREENSHOT_TOKEN";
    const defaultToken = manifest?.auth?.default_token || "";
    const loginPath = manifest?.auth?.login_url || manifest?.auth?.login_page || "";
    const username = manifest?.auth?.username || "";
    const password = manifest?.auth?.password || "";
    const usernameSelector = manifest?.auth?.username_selector || "input[name=\"authName\"]";
    const passwordSelector = manifest?.auth?.password_selector || "input[name=\"authPassword\"]";
    const submitSelector = manifest?.auth?.submit_selector || "button[type=\"submit\"]";
    const resolvedToken = authToken || process.env[tokenEnv] || defaultToken;

    // 3. Ensure Kuri is healthy
    const healthResp = await kuriFetch("/health");
    if (!healthResp.ok) {
      return {
        content: [{ type: "text" as const, text: `Kuri server not responding (${healthResp.status}) — start it first with 'kuri-start' or 'KURI_ALLOW_PRIVATE=1 kuri'` }],
      };
    }

    // 4. Get or create tab
    let tabId = reuseTabId || "";
    let newTabResp = "";
    if (!tabId) {
      newTabResp = await kuriFetchText("/tab/new", { url: "about:blank", activate: "true" });
      try {
        const tabData = JSON.parse(newTabResp);
        tabId = tabData.tab_id || tabData.id || "";
      } catch { /* fall through */ }
    }
    if (!tabId) {
      return {
        content: [{ type: "text" as const, text: `Failed to create Kuri tab. Kuri may not be running. Response: ${newTabResp.slice(0, 200)}` }],
      };
    }

    // 5. Auth is repository-owned manifest behavior, not pi-dev product knowledge.
    if (authMethod === "form-login") {
      const originUrl = manifestBaseUrl.replace(/\/$/, "");
      const loginPageUrl = loginPath.startsWith("http") ? loginPath : originUrl + (loginPath || "/login.php");

      try {
        await kuriFetchText("/navigate", { tab_id: tabId, url: loginPageUrl });
        await new Promise(r => setTimeout(r, 1500));

        await kuriFetchText("/evaluate", {
          tab_id: tabId,
          expression: `document.querySelector(${singleQuotedJsString(usernameSelector)}).value=${JSON.stringify(username)}`,
        });
        await kuriFetchText("/evaluate", {
          tab_id: tabId,
          expression: `document.querySelector(${singleQuotedJsString(passwordSelector)}).value=${JSON.stringify(password)}`,
        });
        await new Promise(r => setTimeout(r, 300));

        await kuriFetchText("/evaluate", {
          tab_id: tabId,
          expression: `document.querySelector(${singleQuotedJsString(submitSelector)}).click()`,
        });

        await new Promise(r => setTimeout(r, 3000));
      } catch (err: any) {
        return {
          content: [{ type: "text" as const, text: `Login failed (${err.message}). The captured screenshot may show an unauthenticated page.` }],
        };
      }
    } else if (authMethod === "bearer-token-session" && resolvedToken && loginPath) {
      const originUrl = manifestBaseUrl.replace(/\/$/, "");
      const loginPageUrl = loginPath.startsWith("http") ? loginPath : originUrl + loginPath;
      await kuriFetchText("/navigate", {
        tab_id: tabId,
        url: loginPageUrl,
        headers: JSON.stringify({ Authorization: `Bearer ${resolvedToken}` }),
      });
      await new Promise(r => setTimeout(r, 1500));
    }

    // 6. Navigate to target
    await kuriFetchText("/navigate", {
      tab_id: tabId,
      url: targetUrl,
    });

    // 7. Settle
    const settle = settleMs ?? manifestSettleMs;
    await new Promise(r => setTimeout(r, settle));

    // 7.5 Full-page mode: resize viewport to full page height so the screenshot
    // captures the entire scrollable document instead of just the viewport.
    // Uses JPEG format for tall pages since Chrome's PNG encoder can OOM.
    // Resets viewport after capture.
    let originalViewport: { w: number; h: number } | null = null;
    let useJpegForTall = false;
    if (fullPage) {
      try {
        const piText = await kuriFetchText("/page/info", { tab_id: tabId }).catch(() => "{}");
        const pi: any = JSON.parse(piText);
        const vw = Number(pi.viewport_width) || 1920;
        const vh = Number(pi.viewport_height) || 1080;
        originalViewport = { w: vw, h: vh };
        const dimText = await kuriFetchText("/evaluate", {
          tab_id: tabId,
          expression: "JSON.stringify({sw:document.documentElement.scrollWidth,sh:document.documentElement.scrollHeight})",
        }).catch(() => "");
        const dimJson: any = JSON.parse(dimText);
        const sw = Number(dimJson?.result?.result?.value ? JSON.parse(dimJson.result.result.value).sw : 0) || vw;
        const sh = Number(dimJson?.result?.result?.value ? JSON.parse(dimJson.result.result.value).sh : 0) || vh;
        if (sh > vh && sh > 0 && sw > 0) {
          useJpegForTall = true;
          await kuriFetch("/set/viewport", { tab_id: tabId, width: String(sw), height: String(sh) });
          // Let the renderer catch up after resize
          await new Promise(r => setTimeout(r, 1000));
        }
      } catch {
        // Best-effort: if viewport resize fails, fall through to normal screenshot
      }
    }

    // 8. Capture advisory page state before screenshot so the reviewer can tell
    // whether auth landed on the expected page or a login wall.
    const pageInfoText = await kuriFetchText("/page/info", { tab_id: tabId }).catch(() => "");
    let pageInfo: any = {};
    try {
      pageInfo = pageInfoText ? JSON.parse(pageInfoText) : {};
    } catch { /* advisory only */ }
    const pageText = await kuriFetchText("/text", { tab_id: tabId }).catch(() => "");
    const warning = loginPageWarning(pageInfo, pageText, targetUrl);

    // 9. Screenshot — use JPEG for tall pages (full-page mode) since
    // Chrome's PNG encoder may OOM on very tall viewport captures
    const screenshotResp = await kuriFetch("/screenshot", {
      tab_id: tabId,
      ...(useJpegForTall ? { format: "jpeg", quality: "30" } : {}),
    });
    const screenshotJson = await screenshotResp.json();
    let pngData: string | undefined;
    if (screenshotJson.result?.result?.data) {
      pngData = screenshotJson.result.result.data;
    } else if (screenshotJson.result?.data) {
      pngData = screenshotJson.result.data;
    } else if (screenshotJson.data) {
      pngData = screenshotJson.data;
    }

    if (!pngData) {
      return {
        content: [{ type: "text" as const, text: `Screenshot failed: Kuri returned an unexpected response format. The page may not have loaded correctly. ${JSON.stringify(screenshotJson).slice(0, 200)}` }],
      };
    }

    // 10. Save PNG — default to ticket-owned Sandcastle evidence, with explicit
    // non-Desktop override allowed.
    const pageSlug = pageName || targetUrl.replace(/[^a-z0-9]/gi, "-").replace(/-+/g, "-").slice(0, 40).toLowerCase();
    let savedPath = outputPath;
    let repoRoot = "";
    let taskKey = "";
    if (!savedPath) {
      const wtMatch = projectRoot.match(/(.+?)\/\.sandcastle\/worktrees\/sandcastle-([A-Z0-9]{2,5})-/i);
      if (wtMatch) {
        repoRoot = wtMatch[1];
        taskKey = wtMatch[2].toLowerCase();
        const stamp = new Date().toISOString().replace(/[:.]/g, "-");
        savedPath = path.join(repoRoot, ".sandcastle", "tickets", taskKey, "evidence", `kuri-${pageSlug}-${stamp}`, "visual-evidence.png");
      } else {
        savedPath = path.join(projectRoot, ".sandcastle", "evidence", "manual", `evidence-${pageSlug}-${Date.now()}.png`);
      }
    }
    const buf = Buffer.from(pngData, "base64");
    const { mkdirSync, writeFileSync } = require("node:fs") as typeof import("node:fs");
    mkdirSync(path.dirname(savedPath), { recursive: true });
    writeFileSync(savedPath, buf);

    // 10.5 Full-page mode: reset viewport to original dimensions
    if (originalViewport) {
      kuriFetch("/set/viewport", {
        tab_id: tabId,
        width: String(originalViewport.w),
        height: String(originalViewport.h),
      }).catch(() => {});
    }

    // Warn if screenshot is suspiciously small (blank/error page)
    if (buf.length < 2000) {
      return {
        content: [{ type: "text" as const, text: `Evidence file ${savedPath} saved (only ${buf.length} bytes — page may be blank or returned an error). Inspect before relying on this evidence.` }],
      };
    }

    let pageTitle = "";
    let pageUrl = "";
    pageTitle = pageInfo.title || "";
    pageUrl = pageInfo.url || "";
    const artifactPath = repoRoot && savedPath.startsWith(repoRoot)
      ? path.relative(repoRoot, savedPath)
      : savedPath;
    const evidenceManifest = {
      status: "passed",
      role: "reviewer",
      screen: targetUrl,
      finalUrl: pageUrl,
      title: pageTitle,
      page: pageName,
      capturedAt: new Date().toISOString(),
      artifacts: [artifactPath],
      checks: [
        { name: "visual evidence", passed: true, detail: "Kuri screenshot captured" },
        { name: "page rendered", passed: true, detail: "document body exists" },
      ],
      warnings: warning ? [warning] : [],
      ...(taskKey ? { taskKey: taskKey.toUpperCase() } : {}),
    };
    const manifestJson = `${JSON.stringify(evidenceManifest, null, 2)}\n`;
    writeFileSync(path.join(path.dirname(savedPath), "visual-evidence.json"), manifestJson);
    writeFileSync(path.join(path.dirname(savedPath), "visual-evidence-manifest.json"), manifestJson);

    return {
      content: [{
        type: "text" as const,
        text: [
          `Evidence file ${savedPath} saved (${buf.length} bytes)`,
          `Manifest ${path.join(path.dirname(savedPath), "visual-evidence-manifest.json")} saved`,
          outputPath ? "Note: output override was used; prefer the default Sandcastle evidence path for ticket handoff." : "",
          authToken ? "Note: token override was used; prefer repository manifest auth/env config." : "",
          warning ? `Warning: ${warning}` : "",
          `Page: ${pageTitle}`,
          `URL: ${pageUrl}`,
        ].filter(Boolean).join("\n"),
      }],
    };
  },
});

const kuriConsoleErrorsTool = kuriTool({
  name: "kuri_console_errors",
  label: "Console Errors",
  description: "Extract recent console.error/warn entries from the browser page. Useful for diagnosing why a page isn't rendering.",
  promptSnippet: "Get browser console errors",
  promptGuidelines: [
    "Use after a page loads but seems empty or broken — checks for JS errors.",
    "If the result is empty, no errors were captured (or the console was cleared).",
  ],
  parameters: Type.Object({
    tab_id: Type.Optional(Type.String({ description: "Optional explicit tab ID." })),
  }),
  execute: async (_toolCallId, params, _signal, _onUpdate) => {
    const expression = [
      "(function(){",
      "  var e = window.__kuriErrorLog || [];",
      "  if (!window.__kuriErrorLog) {",
      "    window.__kuriErrorLog = [];",
      "    var orig = console.error;",
      "    console.error = function() {",
      "      var args = Array.prototype.slice.call(arguments);",
      "      window.__kuriErrorLog.push(args.map(function(a){return typeof a === 'string' ? a : JSON.stringify(a)}).join(' '));",
      "      return orig.apply(console, arguments);",
      "    };",
      "    var origWarn = console.warn;",
      "    console.warn = function() {",
      "      var args = Array.prototype.slice.call(arguments);",
      "      window.__kuriErrorLog.push('[WARN] ' + args.map(function(a){return typeof a === 'string' ? a : JSON.stringify(a)}).join(' '));",
      "      return origWarn.apply(console, arguments);",
      "    };",
      "  }",
      "  return e.length ? e.slice(-30).join('\\n') : '';",
      "  })()",
    ].join("");
    const query: Record<string, string> = { expression };
    if (params.tab_id) query.tab_id = String(params.tab_id);
    const text = await kuriFetchTextWithRetry("/evaluate", query);
    let result = "";
    try {
      const parsed = JSON.parse(text);
      result = parsed?.result?.result?.value || parsed?.result?.value || "";
    } catch {
      result = text;
    }
    if (!result || !String(result).trim()) {
      result = "No console errors captured (console.error interceptor installed).";
    }
    return { content: [{ type: "text" as const, text: String(result) }] };
  },
});

const allTools = [
  kuriNavigateTool,
  kuriSnapTool,
  kuriClickTool,
  kuriTypeTool,
  kuriFillTool,
  kuriSelectTool,
  kuriPageInfoTool,
  kuriScreenshotTool,
  kuriEvaluateTool,
  kuriMarkdownTool,
  kuriLinksTool,
  kuriTextTool,
  kuriConsoleErrorsTool,
  kuriCookiesTool,
  kuriAuditTool,
  kuriNewTabTool,
  kuriScrollTool,
  kuriScrollUpTool,
  kuriScrollDownTool,
  kuriScreenshotSiteTool,
];

// ── Slash command handlers ────────────────────────────────────────────────

function isDuplicateToolConflict(error: unknown): boolean {
  return error instanceof Error && !!error.message?.includes("already defined");
}

async function cmdKuriStart(_args: string, ctx: ExtensionCommandContext): Promise<void> {
  const ok = await checkKuriHealth();
  if (ok) {
    ctx.ui.notify("Kuri server is already running.");
    return;
  }
  ctx.ui.notify("Kuri is not running. Start it manually:\n  kuri\n\nOr with options:\n  PORT=8080 kuri");
}

async function cmdKuriHealth(_args: string, ctx: ExtensionCommandContext): Promise<void> {
  const ok = await checkKuriHealth();
  if (ok) {
    const resp = await kuriFetch("/health");
    const data = await resp.text();
    ctx.ui.notify(`Kuri server is running.\n${data.slice(0, 500)}`);
  } else {
    ctx.ui.notify("Kuri server is NOT running. Start it with: kuri");
  }
}

function cmdKuriTabNew(args: string, ctx: ExtensionCommandContext): void {
  ctx.ui.notify(`Use the kuri_new_tab tool with url="${args.trim() || '<url>'}"`);
}

function cmdKuriNavigate(args: string, ctx: ExtensionCommandContext): void {
  ctx.ui.notify(`Use the kuri_navigate tool with url="${args.trim() || '<url>'}"`);
}

function cmdKuriSnap(_args: string, ctx: ExtensionCommandContext): void {
  ctx.ui.notify("Use the kuri_snap tool with filter=interactive&format=compact");
}

function cmdBase(args: string, ctx: ExtensionCommandContext): void {
  const url = args.trim();
  if (url) {
    process.env.KURI_BASE_URL = url;
    ctx.ui.notify(`KURI_BASE_URL set to ${url}`);
  } else {
    ctx.ui.notify(`Current KURI_BASE_URL: ${kuriBaseUrl()}`);
  }
}

function cmdSession(args: string, ctx: ExtensionCommandContext): void {
  const id = args.trim();
  if (id) {
    process.env.KURI_SESSION = id;
    ctx.ui.notify(`KURI_SESSION set to ${id}`);
  } else {
    ctx.ui.notify(`Current KURI_SESSION: ${kuriSession()}`);
  }
}

function cmdToken(args: string, ctx: ExtensionCommandContext): void {
  const token = args.trim();
  if (token) {
    process.env.KURI_SECRET = token;
    ctx.ui.notify("KURI_SECRET (API auth token) set.");
  } else {
    const current = kuriAuthToken();
    if (current) {
      ctx.ui.notify(`Auth token: ${current.slice(0, 20)}...`);
    } else {
      ctx.ui.notify("No auth token found. Set via KURI_SECRET env var or ~/.kuri/api.token file.");
    }
  }
}

async function cmdGenericKuri(action: string, _args: string, ctx: ExtensionCommandContext): Promise<void> {
  const ok = await checkKuriHealth();
  if (!ok) {
    ctx.ui.notify("Kuri server is not running. Start it first with 'kuri'.");
    return;
  }
  ctx.ui.notify(`Run: kuri_${action} tool`);
}

// ── Extension entry point ────────────────────────────────────────────────

export default function kuriCommands(pi: ExtensionAPI): void {
  for (const tool of allTools) {
    try {
      pi.registerTool(tool);
    } catch (error) {
      if (!isDuplicateToolConflict(error)) {
        throw error;
      }
    }
  }

  // Register /kuri-photo slash command for easy one-shot screenshots
  pi.registerCommand("kuri-photo", {
    description: "One-shot site-manifest screenshot. Usage: /kuri-photo <page-name> [project-root]",
    handler: async (args, ctx) => {
      const parts = args.trim().split(/\s+/);
      const pageName = parts[0] || "<page-name>";
      const projectRoot = parts[1] || process.cwd();
      ctx.ui.notify(`Use the kuri_screenshot_site tool with page="${pageName}" project="${projectRoot}"`);
    },
  });

  pi.on("session_start", async (_event, ctx) => {
    ctx.ui.setStatus("kuri", `🌰 Kuri ${PI_KURI_EXTENSION_VERSION}`);
  });

  pi.on("session_shutdown", async (_event, ctx) => {
    ctx.ui.setStatus("kuri", undefined);
  });

  pi.on("before_agent_start", async (event) => {
    const baseUrl = kuriBaseUrl();
    const sessionId = kuriSession();
    const kuriGuide = [
      "",
      `## Kuri Browser Automation (extension ${PI_KURI_EXTENSION_VERSION})`,
      "",
      "Kuri is a Zig-native browser automation server. Use it only when your role's tool list includes Kuri tools.",
      "If your role does not include `kuri_screenshot_site`, do not attempt browser capture; record the target page, selector, or URL for the verifier/reviewer evidence lane.",
      "",
      "### 1. One-Shot Screenshot (PREFERRED)",
      "",
      'Verifier/reviewer lanes should use `kuri_screenshot_site` for visual evidence. This handles auth, navigation,',
      "settle timing, and evidence PNG saving in a single call:",
      "",
      '  kuri_screenshot_site page="alert-log"            # from .sandcastle/site-manifest.yaml',
      '  kuri_screenshot_site page="dashboard"',
      "",
      "For per-worktree simulators, an explicit URL is also valid:",
      '  kuri_screenshot_site url="$(sandstate sim-url KEY)/indexWEB-ODAS.php#networking"',
      "",
      "Avoid output/token unless the operator explicitly asks for an override.",
      "Never write evidence to Desktop; default output stays under .sandcastle evidence paths.",
      "Read the tool response after capture. If it warns that the page looks like an unauthenticated login page, verify or retry before treating the screenshot as proof.",
      "",
      "When Kuri tools are available, use this first before manual browser tools or gui_* tools.",
      "",
      "### 2. Manual Browser Tools (fallback only if screenshot_site fails)",
      "",
      "Only use these when kuri_screenshot_site cannot reach the right page or state.",
      "",
      "**Open a tab:**",
      "  kuri_new_tab(url?)",
      "",
      "**Check what's on the page:**",
      "  kuri_page_info              — URL, title, ready state",
      "  kuri_snap                   — interactive element refs (e0, e1...)",
      "  kuri_screenshot             — capture screenshot to inspect",
      "",
      "**Act on elements (by ref from snap):**",
      "  kuri_click(ref)             — click element",
      "  kuri_type(ref, value)       — type text",
      "  kuri_fill(ref, value)       — fill input value",
      "  kuri_select(ref, value)     — select dropdown option",
      "  kuri_scroll(direction?)     — scroll page",
      "",
      "**Get page content:**",
      "  kuri_markdown               — page as markdown (auto-resolves tab)",
      "  kuri_links                  — all links (auto-resolves tab)",
      "  kuri_text                   — plain text (falls back to aria-labels on SPAs)",
      "  kuri_evaluate(expression)   — run JavaScript",
      "  kuri_console_errors         — diagnose JS errors when page is empty/broken",
      "",
      "**Tips:**",
      "  - CDP-fragile endpoints auto-retry (up to 3 attempts) on transient failures.",
      "  - Heavy JS pages: add settle_ms=5000 to kuri_screenshot for settle time.",
      "  - Re-snap after navigation or DOM changes — refs are snapshot-local.",
      "",
    ].join("\n");
    return {
      systemPrompt: `${event.systemPrompt}\n${kuriGuide}`,
    };
  });

  pi.registerCommand("kuri", {
    description: "Open the Kuri command picker",
    handler: async (_args, ctx) => {
      const choice = await ctx.ui.select("Kuri commands", MENU_CHOICES);
      if (!choice) return;
      const prefix = choice.split(" - ")[0];
      ctx.ui.setStatus("kuri", `selected: ${prefix}`);
    },
  });

  pi.registerCommand("kuri-help", {
    description: "Show registered Kuri commands",
    handler: async (_args, ctx) => {
      ctx.ui.notify(COMMAND_HELP.join("\n"));
    },
  });

  pi.registerCommand("kuri-start", {
    description: "Check or start the Kuri server",
    handler: cmdKuriStart,
  });

  pi.registerCommand("kuri-health", {
    description: "Check Kuri server health",
    handler: cmdKuriHealth,
  });

  pi.registerCommand("kuri-tab-new", {
    description: "Open a new browser tab and optionally navigate to a URL",
    handler: cmdKuriTabNew,
  });

  pi.registerCommand("kuri-navigate", {
    description: "Navigate the current tab to a URL",
    handler: cmdKuriNavigate,
  });

  pi.registerCommand("kuri-snap", {
    description: "Get accessibility snapshot with interactive refs",
    handler: cmdKuriSnap,
  });

  pi.registerCommand("kuri-session", {
    description: "Set the active Kuri session ID",
    handler: cmdSession,
  });

  pi.registerCommand("kuri-base", {
    description: "Set the Kuri server base URL",
    handler: cmdBase,
  });

  pi.registerCommand("kuri-token", {
    description: "Show or set the Kuri API auth token",
    handler: cmdToken,
  });

  // Register convenience forwarders for common commands
  for (const action of ["page-info", "click", "type", "fill", "select", "screenshot",
    "markdown", "links", "text", "evaluate", "cookies", "audit",
    "back", "forward", "reload"]) {
    const cmdName = `kuri-${action}`;
    const handler = async (_args: string, ctx: ExtensionCommandContext) => {
      await cmdGenericKuri(action.replace("-", "_"), _args, ctx);
    };
    pi.registerCommand(cmdName, {
      description: `Browser: ${action}`,
      handler,
    });
  }
}
